### ISSUE TITLE
Something went wrong when trying to book timeslot

### ISSUE THREAD

**Issue by dst6se** [kalkih/passport-appointment-bot#1] opened 2022-03-21 21:37 UTC
Every time i find a timeslot this error appear 

[22:35:59] [error]      Something went wrong when trying to book timeslot
[22:35:59] [error]      Failed booking slot 2022-10-12 12:20:00

**Comment by xxandeer** [comment] 2022-03-22 01:29
The problem is that "Uppgifter till bokningen" has different values in the Förnamn and Efternamn fields depending on wich region your searching in.

**Comment by dst6se** [comment] 2022-03-22 08:07
Thanks for your help!
Customers[0].Services[0].ServiceId was different !

**Comment by kalkih** [comment] 2022-03-23 09:28
Now fixed

**Closed by kalkih** 2022-03-23 09:28 UTC
Labels: bug
