### ISSUE TITLE
Cannot book anymore

### ISSUE THREAD

**Issue by MarcusWidle** [kalkih/passport-appointment-bot#12] opened 2022-04-01 09:50 UTC
Hello!

It seems like they have added a mtcaptcha which seems to return 404 now. Is it something you have noticed perhaps?

**Comment by xxandeer** [comment] 2022-04-01 10:11
@MarcusWidle I've also noticed that its not longer works. I dont know if there is possible to get it to work now when the recaptcha was implemented. We have to wait and see if @kalkih have any solution for this.

**Comment by 3kgtt** [comment] 2022-04-01 10:43
Tack för arbetet och tiden. Funkade igår och en kort stund tidigt på morg. Nu visar den bara 0 i alla sökningar :(

**Comment by kalkih** [comment] 2022-04-01 10:56
Will check on the changes made to the booking system tonight and see what can be done. 🤞🏼

**Comment by xxandeer** [comment] 2022-04-01 11:00
Perfect @kalkih, maybe they've changed something in the layout since we still seems to reach the pages with the script.
I saw a comment in another project where someone mentioned that there was changes in their layout also.

**Comment by MarcusWidle** [comment] 2022-04-01 11:03
I have myself checked the requests both with Burp and Charles and I can see the only thing that has been added is mtcaptcha-validate... - You will get the same response if you e.g. disable the JS which makes the captcha go away and when you submit. You will get an error "För många..." something something... for some reason when trying to use the same cURL. It returns 404. when manually adding the valid mtcaptcha token, it works fine. Hence why my guess sits on the mtcaptcha. Either needs to be reversed or other bypasses.

**Comment by 3kgtt** [comment] 2022-04-01 11:08
From what i see in this topic. 
[https://github.com/jonkpirateboy/Pass-fur-alle/issues/42](url)
They are too trying to fix this. And its caused by both captcha + searching time. 
This is in my opinion the best working app for windows. So hopefully it can be fixed.

**Comment by MarcusWidle** [comment] 2022-04-01 11:10
> From what i see in this topic. [https://github.com/jonkpirateboy/Pass-fur-alle/issues/42](url) They are too trying to fix this. And its caused by both captcha + searching time. This is in my opinion the best working app for windows. So hopefully it can be fixed.

However we cannot compare with Pass fur alle due to they are using Selenium and we are using requests which is not the same thing. Would make sense if we used Puuppert (Not sure if I spelled it right. ;P) but the scenario here is different

**Comment by kalkih** [comment] 2022-04-01 22:32
Unfortunately I couldn't manage to bypass the captchas, so a manual captcha step was added in order for the bot to still function, more information can be found in the [v3.0.0 release](https://github.com/kalkih/passport-appointment-bot/releases/tag/v3.0.0).

Tested on Windows & MacOS and seems to work as expected.

Let me know how it works, all feedback is appreciated.

**Comment by kalkih** [comment] 2022-04-01 22:35
Will play around with "Caching" captchas, but they do most likely have a quite short expiration time, so might not be of any use.

The idea of caching them would be to let the user solve a few captchas at startup, the captcha resolutions could then be used whenever the page requires the captcha in the booking step e.t.c.

**Comment by TheRobban02** [comment] 2022-04-02 09:27
Got Error 1415 and an error message covering the captcha. Is there any solution for this?

**Comment by kalkih** [comment] 2022-04-02 15:16
Well, that solution didn't last long... 🙂

**Comment by kalkih** [comment] 2022-04-02 15:23
Closing in favor for #15

**Closed by kalkih** 2022-04-02 15:23 UTC
